# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reviews', '0002_auto_20170420_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(default='$2b$12$pTnZS9g9dWx1ZveqSkHL5e', max_length=100),
        ),
    ]
